---
title: "Exploration - groups, other variables"
author: "Cassandra Wattenburger"
date: "3/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(results = "show")
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```

**Goal of this script:** See if any other growth dynamics variables separate into two groups.


# Import libraries

```{r}
library(tidyverse)
library(mclust)

sessionInfo()

rm(list=ls())

set.seed(2) # mclust uses EM algorhythm which is iterative and random
```


# Import data

```{r}
growth <- readRDS("rdata.files/gr_gr.paprica.clean.rds")
```

Average across replicates to get a single estimated growth rate for each taxa in each treatment.

```{r}
# Average across replicates for each ASV
growth.asv <- growth %>%
  group_by(Soil, Amendment, ASV) %>%
  summarize(k = mean(k),
            start_day = mean(start_day),
            end_day = mean(end_day),
            start_abund = mean(start_abund),
            end_abund = mean(end_abund))

# Including PAPRICA results
# Have to remove archaea because they weren't predicted by program (NAs)
growth.paprica.asv <- growth %>%
  na.omit() %>%
  group_by(Soil, Amendment, ASV) %>%
  summarize(k = mean(k),
            start_day = mean(start_day),
            end_day = mean(end_day),
            start_abund = mean(start_abund),
            end_abund = mean(end_abund),
            n16S = mean(n16S),
            genome_size = mean(genome_size))
```


Visualize distributions:

```{r}
# Averaged across replicates
growth.paprica.asv %>%
  ggplot(aes(x=log(start_day), color=Soil)) +
  geom_density() +
  facet_wrap(~Amendment) +
  labs(title="Start day") +
  theme_test()

growth.paprica.asv %>%
  mutate(change_abund = end_abund - start_abund) %>%
  ggplot(aes(x=log(change_abund), color=Soil)) +
  geom_density() +
  facet_wrap(~Amendment) +
  labs(title="Change in abundance") +
  theme_test()

growth.paprica.asv %>%
  ggplot(aes(x=log(n16S), color=Soil)) +
  geom_density() +
  facet_wrap(~Amendment) +
  labs(title="n16S") +
  theme_test()
```

Looks like not.