---
title: "Exploration - misc."
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(results = "show")
knitr::opts_chunk$set(message = FALSE)
```

```{r}
rm(list=ls())

library("phyloseq")
library("tidyverse")

sessionInfo()
```

# Comparing estimated to non-estimated taxon abundances at tp0

Import data

```{r}
# Normalized abundance data
load("../rdata.files/gr_microcosm.norm.tax.RData")
norm <- microcosm.norm.tax %>% 
  select(everything(), Amendment=Cammend, ASV=variable)

# Growth estimates
growth <- readRDS("../rdata.files/gr_gr.paprica.clean.rds")
```

Isolate estimated and non-estimated ASVs

```{r}
est_yes <- norm %>% 
  semi_join(growth, by=c("ASV", "Soil", "Amendment")) %>% 
  filter(Days==0) %>% 
  add_column(Estimated = "yes")
  
est_no <- norm %>% 
  anti_join(growth, by=c("ASV", "Soil", "Amendment")) %>% 
  filter(Days==0) %>% 
  add_column(Estimated = "no")

tp0_abund <- bind_rows(est_yes, est_no)
```

Graph abundances at tp0

```{r}
tp0_abund %>% 
  ggplot(aes(x=Estimated, y=log(value))) +
  geom_boxplot() +
  geom_jitter(alpha=0.5) +
  theme_test()
```

Information about example time series in Figure 1

```{r}
growth_examples <- growth %>% 
  filter((Soil=="S17" & Amendment=="Y" & Replicate == 1 & ASV=="13e4a5f455c50b2e805e017ca450ade2") |
           (Soil=="C3" & Amendment=="Y" & Replicate == 3 & ASV=="aecae9d790a63cf565c1b5cdbd02ebdd") |
           (Soil=="C3" & Amendment=="N" & Replicate == 1 & ASV=="692a26188cb2e4528d0add62ea0d77f1") |
           (Soil=="S17" & Amendment=="Y" & Replicate == 3 & ASV=="4b2544b81a01a3355506bfbba84889e1")) %>% 
  arrange(start_day) %>% 
  mutate(change_abund = end_abund - start_abund)
```

